# Generated by Django 2.0.2 on 2018-02-28 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allobouffe', '0002_auto_20180227_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='image',
        ),
    ]
